name: work
labels: ["work"]
assignees:
    - littleswampman
description: work issue
body:
    - type: dropdown
      id: priority
      attributes:
          label: What is the priority?
          # description:
          multiple: false
          options:
              - "top"
              - "high"
              - "low"
      validations:
          required: true
    - type: dropdown
      id: type-of-work
      attributes:
          label: What is the type of work?
          # description:
          multiple: true
          options:
              - "coding"
              - "writing"
              - "designing"
              - "other"
      validations:
          required: true
    - type: textarea
      id: work-detail
      attributes:
          label: Please explain the details of the work.
          # description:
          placeholder: "Example: There's not enough time."
          # value:
          render: Markdown
      validations:
          required: true
